export interface Cliente {
    idCliente?:number,
    nombre?:string,
    fachadaimg?: string,
    url?:string,
    direccion?:string,
    contacto?: string,
    razonSocial?:string,
    idauditor?: number,
    descripcionAuditor?:string,
    detalle?:string,
    esActivo?: number,
    fecha?:string,
    idProspecto?: number,
    descripcionProspecto?:string,
    fechaRegistro:string
}
/*{
  "idCotizacion": 0,
  "idProspecto": 0,
  "descripcionProspecto": "string",
  "pulgadas2": 0,
  "tipoPago": "string",
  "totalTexto": "string",
  "tiempoFinancing": 0,
  "ahorraTexto": "string",
  "valorInteresesTexto": "string",
  "cuotaMensualTexto": "string",
  "pagoElectricidadTexto": "string",
  "porcentajeIncremento": 0,
  "mensualAproxTexto": "string",
  "valorPagadoTexto": "string",
  "proyeccionSolarTexto": "string",
  "tiempoSolar": 0,
  "contrato": "string",
  "email": "string",
  "tipoIdentificacion": "string",
  "identificacion": 0,
  "socEin": 0,
  "tamanoSistema": "string",
  "pagoInicialTexto": "string",
  "notas": "string",
  "url1": "string",
  "url2": "string",
  "url3": "string",
  "url4": "string",
  "pdf": "string",
  "fechaRegistro": "string"
}*/