import { Servicio } from "./servicio";

export interface Cotizacion {
  idCotizacion?:number,
  idProspecto?:number,
  descripcionProspecto?:string,
  pulgadas2?:number,
  tipoPago?: string,
  totalTexto?:string,
  tiempoFinancing?:number,
  ahorraTexto?:string,
  valorInteresesTexto?: string,
  cuotaMensualTexto?:string,
  pagoElectricidadTexto:string,
  porcentajeIncremento?: number,
  mensualAproxTexto?:string,
  valorPagadoTexto?:string,
  proyeccionSolarTexto:string,
  tiempoSolar?: number,
  contrato?:string,
  email?:string,
  tipoIdentificacion:string,
  identificacion?: number,
  socEin?:number,
  tamanoSistema?:string,
  pagoInicialTexto?: string,
  notas?:string,
  url1?:string,
  url2?:string,
  url3?:string,
  url4?:string,
  pdf?:string,
  fechaRegistro?:string,
  Servicios?: Servicio[]
}
/*{
"idCotizacion": 0,
"idProspecto": 0,
"descripcionProspecto": "string",
"pulgadas2": 0,
"tipoPago": "string",
"totalTexto": "string",
"tiempoFinancing": 0,
"ahorraTexto": "string",
"valorInteresesTexto": "string",
"cuotaMensualTexto": "string",
"pagoElectricidadTexto": "string",
"porcentajeIncremento": 0,
"mensualAproxTexto": "string",
"valorPagadoTexto": "string",
"proyeccionSolarTexto": "string",
"tiempoSolar": 0,
"contrato": "string",
"email": "string",
"tipoIdentificacion": "string",
"identificacion": 0,
"socEin": 0,
"tamanoSistema": "string",
"pagoInicialTexto": "string",
"notas": "string",
"url1": "string",
"url2": "string",
"url3": "string",
"url4": "string",
"pdf": "string",
"fechaRegistro": "string"
}*/